apiVersion: v1
kind: Service
metadata:
 name: theia
spec:
 ports:
 - port: 80
   targetPort: 3000
 selector:
   app: theia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: theia
  name: theia
spec:
  selector:
    matchLabels:
      app: theia
  replicas: 1
  template:
    metadata:
      labels:
        app: theia
    spec:
      containers:
      - image: juouyang/theia-ansible
        imagePullPolicy: Always
        name: theia
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: "/home/project"
            name: theia-project
          - mountPath: "/home/theia/.ansible"
            name: cache-volume
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: theia-project
        persistentVolumeClaim:
          claimName: theia-project-vol
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: theia-project-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: longhorn
