- hosts: all
  gather_facts: true
  tasks:
  - name: run tasks on localhost
    block:
    - name: ensure tmp folder existed
      file:
        path: $PWD/tmp
        state: directory
        mode: '0755'
    - copy:
        content: "{{ ansible_facts | to_nice_yaml }}"
        dest: "./tmp/{{ ansible_facts.hostname | default('not_found') }}.yaml"
    delegate_to: localhost

  - set_fact:
      macaddr: "{{ ansible_facts.default_ipv4.macaddress }}"
  - set_fact:
      is_vm: "{{ 'true' if ansible_facts.virtualization_role == 'guest' else 'false' }}"
    when: ansible_facts
  - debug:
      msg:
      - "default_ipv4_mac = {{ macaddr }}"
      - "is_vm = {{ is_vm }}"

  - block:
    - set_fact:
        virtualization: ansible_facts.virtualization_type
    - debug: var="{{ virtualization }}"
    - fail:
    when: is_vm | bool and is_vm is defined and ansible_facts
    ignore_errors: yes

  - set_fact:
      device_list: "{{ device_list | default([]) + [{ item.key : item.value.size }] }}"
    when: "'dm' not in item.key"
    loop: "{{ ansible_facts.devices | dict2items }}"
  - debug:
      msg: "{{ device_list }}"

  - include_tasks: listening.yaml
    vars:
      tcp_blacklist:
      - 22
