- name: "include vs import"
  hosts: all
  gather_facts: false
  collections:
  - testing.sample

  tasks:
  - import_role:
      name: sample
    vars:
      test_message1: "hello"
      test_message2: "role"
    tags:
    - import

  - include_role:
      name: sample
      apply:
        tags: include
    vars:
      test_message1: "hello"
      test_message2: "role"
    tags:
    - include

  - name: Output paramters
    ansible.builtin.debug:
      msg: "caller( {{ test_message1 }}, {{ test_message2 }} )"
    tags:
    - stdout
