- name: Gather facts on listening ports
  community.general.listen_ports_facts:

- name: List TCP ports
  ansible.builtin.debug:
    msg: "{{ ansible_facts.tcp_listen | map(attribute='port') | sort | list }}"

- name: List UDP ports
  ansible.builtin.debug:
    msg: "{{ ansible_facts.udp_listen | map(attribute='port') | sort | list }}"

- name: List all ports
  ansible.builtin.debug:
    msg: "{{ (ansible_facts.tcp_listen + ansible_facts.udp_listen) | map(attribute='port') | unique | sort | list }}"

- name: Gather facts on all ports and override which command to use
  community.general.listen_ports_facts:
    command: 'netstat'
    include_non_listening: true

- set_fact:
    violation_port_list: []

- name: TCP blacklist violation
  set_fact:
    violation_port_list: '{{ violation_port_list + [  item.address | string + ":" + item.port | string + " by pid " + item.pid | string ] }}'
  vars:
    tcp_listen_violations: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', tcp_blacklist) | list }}"
    tcp_blacklist:
      - 23
      - 80
      - 443
  when: item.state == "LISTEN"
  loop: "{{ tcp_listen_violations }}"

- debug:
    msg: "violation_port_list {{ violation_port_list }}"
