- name: run tasks on localhost
  hosts: localhost
  gather_facts: false
  tasks:
  - debug:
      msg:
        - "x is {{ 'not defined' if x is not defined else 'defined' }}"

  - block:
    - debug:
        msg: "call set-x"
    - set_fact:
        x: "data"
    - debug:
        var: x
    when: x is not defined

  - debug:
      msg:
        - "x is {{ 'not defined' if x is not defined else 'defined' }}"

