- name: "Play 1: say 'hello world'"
  hosts: localhost
  tasks:
  - name: echo 'hello world'
    command: echo 'hello world'
    register: result
  - name: print stdout
    debug:
      msg: "{{ result.stdout }}"

- name: "Play 2: ping"
  hosts: localhost
  tasks:
  - ping:
    register: result
  - name: print stdout
    debug:
      msg: "{{ result }}"
